name: weather_clone_app
description: A Flutter weather application
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  percent_indicator: ^4.2.3
  intl: ^0.19.0
  provider: ^6.1.2
  shared_preferences: ^2.5.3
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.2.5
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  flutter_map_cache: ^1.0.1
  cached_network_image: ^3.3.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: ^2.8.7
  flutter_lints: ^2.0.0  # Add this line

flutter:
  generate: true
  uses-material-design: true